apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ayq4seg9m-dotnet-basic
  janus-idp.io/tekton: ayq4seg9m-dotnet-basic
  backstage.io/kubernetes-id: ayq4seg9m-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ayq4seg9m-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
